// Local verification harness, not a ChatGPT installation or a public endpoint.
import {createServer} from 'node:http';
import {readFileSync} from 'node:fs';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
const client=new Client({name:'local-ui-preview',version:'1.0.0'});
await client.connect(new StdioClientTransport({command:process.execPath,args:['plugin/dist/server.mjs']}));
const page=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FlashForge plugin preview</title><style>body{margin:0;background:#101411;color:#ddd;font:14px Arial}aside{padding:12px;border-bottom:1px solid #444}iframe{width:100%;height:1600px;border:0}</style></head><body><aside>LOCAL MCP APPS PREVIEW • Not installed in ChatGPT</aside><iframe id="widget" src="/widget" title="FlashForge dashboard"></iframe><script>
const frame=document.getElementById('widget');addEventListener('message',async e=>{if(e.source!==frame.contentWindow)return;const m=e.data;if(!m||m.jsonrpc!=='2.0'||m.id==null)return;let result;try{if(m.method==='ui/initialize')result={protocolVersion:m.params.protocolVersion,hostInfo:{name:'local-preview',version:'1.0.0'},hostCapabilities:{serverTools:{}},hostContext:{theme:'dark',displayMode:'inline'}};else if(m.method==='tools/call'){const r=await fetch('/call',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(m.params)});result=await r.json();}else if(m.method==='ping')result={};else throw Error();frame.contentWindow.postMessage({jsonrpc:'2.0',id:m.id,result},location.origin);}catch{frame.contentWindow.postMessage({jsonrpc:'2.0',id:m.id,error:{code:-32603,message:'Preview request failed'}},location.origin);}});
</script></body></html>`;
createServer(async(req,res)=>{if(req.url==='/'){res.writeHead(200,{'Content-Type':'text/html'}).end(page);return;}if(req.url==='/widget'){res.writeHead(200,{'Content-Type':'text/html'}).end(readFileSync('plugin/dist/dashboard.html'));return;}if(req.url==='/call'&&req.method==='POST'){try{let body='';for await(const chunk of req){body+=chunk;if(body.length>4096)throw Error();}const args=JSON.parse(body);if(!['get_print_thumbnail','get_printer_status','list_stored_prints','prepare_stored_print','start_stored_print'].includes(args.name))throw Error();res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify(await client.callTool({name:args.name,arguments:args.arguments??{}})));}catch{res.writeHead(400).end('{}');}return;}res.writeHead(404).end();}).listen(8788,'127.0.0.1',()=>console.log('Plugin preview: http://127.0.0.1:8788'));
